In [2]:
import polars as pl 
import io
from contextlib import redirect_stderr
from pathlib import Path

In [3]:
file_path = Path("C:/Users/23225959/dev/ldd/static/reports/KE_QoS_Report_20260303.xlsx")
with io.StringIO() as buf, redirect_stderr(buf):
    df = pl.read_excel(file_path, sheet_name="KE")
df.head()

shape: (5, 183)
┌──────┬────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ OPCO ┆ KPI    ┆ Measurement ┆ 04-09-2025 ┆ … ┆ 28-02-2026 ┆ 01-03-2026 ┆ 02-03-2026 ┆ 03-03-2026 │
│ ---  ┆ ---    ┆ ---         ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str  ┆ str    ┆ str         ┆ str        ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞══════╪════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ KE   ┆ 2G RNA ┆ 24 Hrs      ┆ 99.9111295 ┆ … ┆ 99.8536067 ┆ 99.8537304 ┆ 99.8983107 ┆ 99.8473653 │
│      ┆        ┆             ┆ 61         ┆   ┆ 07         ┆ 43         ┆ 53         ┆ 02         │
│ KE   ┆ 3G RNA ┆ 24 Hrs      ┆ 99.91      ┆ … ┆ 99.85      ┆ 99.85      ┆ 99.9       ┆ 99.85      │
│ KE   ┆ 4G RNA ┆ 24 Hrs      ┆ 99.906476  ┆ … ┆ 99.847346  ┆ 99.846147  ┆ 99.898214  ┆ 99.850067  │
│ KE   ┆ 5G RNA ┆ 24 Hrs      ┆ 99.97      ┆ … ┆ 99.94      ┆ 99.93      ┆ 99.93      ┆ 99.9       │
│ KE   ┆ 2G DCR ┆ 24 Hrs      ┆ 0.29       ┆ … ┆ 0.32       ┆ 0.33       ┆ 0.31       ┆ 0.31       │
└──────┴────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [6]:
df.write_json("new.json")
df.write_parquet("new.parquet")

In [5]:
another_df = pl.read_json("new.json")
another_df.head()

shape: (5, 183)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 01-11-202 ┆ 14-11-202 ┆ 21-09-202 ┆ 28-12-202 ┆ … ┆ 20-10-202 ┆ 23-11-202 ┆ 23-12-202 ┆ 14-01-20 │
│ 5         ┆ 5         ┆ 5         ┆ 5         ┆   ┆ 5         ┆ 5         ┆ 5         ┆ 26       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 99.925250 ┆ 99.938036 ┆ 99.923717 ┆ 99.908280 ┆ … ┆ 99.948517 ┆ 99.919222 ┆ 99.948022 ┆ 99.92635 │
│ 411       ┆ 873       ┆ 271       ┆ 893       ┆   ┆ 051       ┆ 462       ┆ 975       ┆ 4668     │
│ 99.93     ┆ 99.94     ┆ 99.92     ┆ 99.91     ┆ … ┆ 99.95     ┆ 99.92     ┆ 99.95     ┆ 99.93    │
│ 99.925336 ┆ 99.936164 ┆ 99.915398 ┆ 99.90723  ┆ … ┆ 99.947296 ┆ 99.917152 ┆ 99.95108  ┆ 99.93309 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ 99.98     ┆ 99.97     ┆ 99.96     ┆ 99.95     ┆ … ┆ 99.97     ┆ 99.97     ┆ 99.97     ┆ 99.98    │
│ 0.32      ┆ 0.3       ┆ 0.31      ┆ 0.31      ┆ … ┆ 0.3       ┆ 0.31      ┆ 0.29      ┆ 0.3      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
another_new_df = pl.read_parquet("new.parquet")
another_new_df

shape: (572, 183)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ OPCO    ┆ KPI        ┆ Measureme ┆ 04-09-202 ┆ … ┆ 28-02-202 ┆ 01-03-202 ┆ 02-03-202 ┆ 03-03-202 │
│ ---     ┆ ---        ┆ nt        ┆ 5         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ 6         │
│ str     ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆            ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ KE      ┆ 2G RNA     ┆ 24 Hrs    ┆ 99.911129 ┆ … ┆ 99.853606 ┆ 99.853730 ┆ 99.898310 ┆ 99.847365 │
│         ┆            ┆           ┆ 561       ┆   ┆ 707       ┆ 443       ┆ 753       ┆ 302       │
│ KE      ┆ 3G RNA     ┆ 24 Hrs    ┆ 99.91     ┆ … ┆ 99.85     ┆ 99.85     ┆ 99.9      ┆ 99.85     │
│ KE      ┆ 4G RNA     ┆ 24 Hrs    ┆ 99.906476 ┆ … ┆ 99.847346 ┆ 99.846147 ┆ 99.898214 ┆ 99.850067 │
│ KE      ┆ 5G RNA     ┆ 24 Hrs    ┆ 99.97     ┆ … ┆ 99.94     ┆ 99.93     ┆ 99.93     ┆ 99.9      │
│ KE      ┆ 2G DCR     ┆ 24 Hrs    ┆ 0.29      ┆ … ┆ 0.32      ┆ 0.33      ┆ 0.31      ┆ 0.31      │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Eldoret ┆ 4G L800    ┆ DBBH      ┆ 83.7      ┆ … ┆ 68.73     ┆ 67.64     ┆ 75.18     ┆ 74.55     │
│         ┆ (% cells   ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ with >5    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ Mbp…       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Eldoret ┆ 4G L900 (% ┆ DBBH      ┆ NA        ┆ … ┆ NA        ┆ NA        ┆ NA        ┆ NA        │
│         ┆ cells with ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ >5Mbps u…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Eldoret ┆ 4G L1800   ┆ DBBH      ┆ 96.93     ┆ … ┆ 90.6      ┆ 91.45     ┆ 92.31     ┆ 93.16     │
│         ┆ (% cells   ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ with >5    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ Mbps…      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Eldoret ┆ 4G L2100   ┆ DBBH      ┆ 97.33     ┆ … ┆ 92.74     ┆ 92.31     ┆ 93.16     ┆ 94.87     │
│         ┆ (% cells   ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ with >5    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ Mbps…      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Eldoret ┆ 4G L2600   ┆ DBBH      ┆ 100       ┆ … ┆ 99.19     ┆ 100       ┆ 100       ┆ 100       │
│         ┆ (% cells   ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ with >5    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ Mbps…      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘